# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false
  config.vm.define "k8s-master" do |k|
    k.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
      vb.name = "k8s-master"
    end
    k.vm.hostname = "k8s-master"
    k.vm.network "private_network", ip: "192.168.56.10"
    k.vm.synced_folder "./", "/vagrant", disable: false
    k.vm.provision "ansible" do |ansible|
      ansible.config_file = "./ansible.cfg"
      ansible.playbook = "./site.yml"
      ansible.inventory_path = "./inventory.yml"
    end
  end
end
