---
- name: Establish hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: ensure hostname entry in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present
